### ISSUE TITLE
Development code left in

### ISSUE THREAD

**Issue by pHiney** [hudmol/as_reftracker#1]
In backend/model/reftracker_client.rb
lines 36 - 42 are commented out and a "fake it" line is in

No one else has a '/Users/james/projects/nla/data/reftracker_offer_NLAacq87747.json'

There is more commented code in the 'else' stanza of the same if statement in that file, ending in a reference to '/Users/james/projects/nla/data/reftracker_offers_sorted.json'

Can the correct code be uncommented please ?

thanks
Peter

**Comment by jambun** [comment]
Done. Apologies - test code committed in error while updating the readme.
