### ISSUE TITLE
require 'Date' should be lowercase 

### ISSUE THREAD

**Issue by bdsilvaNLA** [hudmol/as_reftracker#2]
require 'Date' should be lowercase 

INFO: INFO: resetting rack response due exception: org.jruby.rack.RackInitializationException: no such file to load -- Date

**Comment by jambun** [comment]
Sorry @bdsilvaNLA - that's pretty lame. Fixed and a new release:
https://github.com/hudmol/as_reftracker/releases/tag/v2.4
